services:
  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  bd1:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: bd1
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - ../sql/bd1_postgres.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  bd2:
    image: mariadb:10.11
    container_name: mariadb
    environment:
      MARIADB_DATABASE: bd2
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - ../sql/bd2_mariadb.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - default
    
  cliente-simulador:
    build:
      context: ../cliente-nodo
    container_name: cliente-simulador
    depends_on:
      - rabbitmq
    tty: true
    stdin_open: true

  servicio_bd1:
    container_name: service-bd1
    build:
      context: ../servicio-bd1-python
    depends_on:
      - rabbitmq
      - bd1
    command: python consumer_bd1.py

  servicio_bd2:
    container_name: service-bd2
    build:
      context: ../servicio-bd2-java
    depends_on:
      - rabbitmq
      - bd2
