CREATE TABLE IF NOT EXISTS usuarios (
  id SERIAL PRIMARY KEY,
  nombre  VARCHAR(30) NOT NULL,
  correo VARCHAR(30) NOT NULL,
  clave VARCHAR(30) NOT NULL,
  dni VARCHAR(8) UNIQUE NOT NULL,
  telefono VARCHAR(9) UNIQUE NOT NULL,
  amigos INTEGER[] DEFAULT '{}'
);